### ISSUE TITLE
How are the peaksets in Y-axis sorted and ranked?

### ISSUE THREAD

**Issue by bijuissacch224610** [teunbrand/tornadoplot#1]
Hi

I have a question on the plots
In the tornado plots, are the peaksets in Y-axis sorted and ranked in any way?

Best
-Biju

**Comment by teunbrand** [comment]
Hi there,

If you're using the `tornado_plot()` function as in the README file, the peaks get sorted within a peakset by default.
The function that performs the sorting is the `sort_tornado()` function, which by default will take a weighted sum of every peak across all samples. The default weighting scheme follows a Laplace distribution density function centered at the middle of the bins and the scale parameter is 10% of the number of the bins. In other words, the sorting is biased towards the centers of peaks and the periphery contributes less. To turn off sorting and preserve the order of the peaks in which they're given, you should be able to use `tornado_plot(..., sort = FALSE)`.

Best,
Teun

**Comment by bijuissacch224610** [comment]
Thank you very much.
